# Generated by Django 3.2.23 on 2025-01-20 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('COAX MODEM', 'Coax Modem'), ('FIBER MODEM', 'Fiber Modem'), ('ROUTER 6', 'Router 6'), ('ROUTER 6E', 'Router 6E'), ('ROUTER 7', 'Router 7'), ('WIB', 'Wib'), ('HD', 'Hd'), ('DVR', 'Dvr'), ('XUMO', 'Xumo')], max_length=100, null=True)),
                ('identifier', models.CharField(max_length=100, unique=True)),
                ('is_return', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='job.job')),
            ],
        ),
    ]
