# Generated by Django 5.1.4 on 2025-02-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_alter_list_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
