# Generated by Django 5.1.4 on 2025-02-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_listitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
