# Generated by Django 3.2.23 on 2025-01-20 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('compensation', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(max_length=10, unique=True)),
                ('type', models.CharField(choices=[(1, 'Nc Single'), (2, 'Nc Double'), (3, 'Nc Triple'), (4, 'Rc Single'), (5, 'Rc Double'), (6, 'Rc Triple'), (7, 'Res Single'), (8, 'Res Double'), (9, 'Res Triple'), (10, 'Trouble Call'), (11, 'Down Drop'), (12, 'Sb Nc Single'), (13, 'Sb Nc Double'), (14, 'Sb Nc Triple'), (15, 'Sb Rc Single'), (16, 'Sb Rc Double'), (17, 'Sb Rc Triple')], max_length=100)),
                ('time_frame', models.CharField(choices=[('8-9AM', '8:00 AM - 9:00 AM'), ('9-10AM', '9:00 AM - 10:00 AM'), ('10-11AM', '10:00 AM - 11:00 AM'), ('11AM-12PM', '11:00 AM - 12:00 PM'), ('12-1PM', '12:00 PM - 1:00 PM'), ('1-2PM', '1:00 PM - 2:00 PM'), ('2-3PM', '2:00 PM - 3:00 PM'), ('3-4PM', '3:00 PM - 4:00 PM'), ('4-5PM', '4:00 PM - 5:00 PM'), ('5-6PM', '5:00 PM - 6:00 PM'), ('6-7PM', '6:00 PM - 7:00 PM'), ('7-8PM', '7:00 PM - 8:00 PM'), ('8-9PM', '8:00 PM - 9:00 PM')], default='0', max_length=100)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='address.address')),
            ],
        ),
    ]
