# Generated by Django 3.2.23 on 2025-01-22 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_job_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateField(verbose_name=datetime.datetime(2025, 1, 21, 20, 43, 18, 261853)),
        ),
        migrations.AlterField(
            model_name='job',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
