# Generated by Django 5.1.4 on 2025-02-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_alter_job_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='time_frame',
            field=models.CharField(blank=True, choices=[('8-9AM', '8:00 AM - 9:00 AM'), ('9-10AM', '9:00 AM - 10:00 AM'), ('10-11AM', '10:00 AM - 11:00 AM'), ('11AM-12PM', '11:00 AM - 12:00 PM'), ('12-1PM', '12:00 PM - 1:00 PM'), ('1-2PM', '1:00 PM - 2:00 PM'), ('2-3PM', '2:00 PM - 3:00 PM'), ('3-4PM', '3:00 PM - 4:00 PM'), ('4-5PM', '4:00 PM - 5:00 PM'), ('5-6PM', '5:00 PM - 6:00 PM'), ('6-7PM', '6:00 PM - 7:00 PM'), ('7-8PM', '7:00 PM - 8:00 PM'), ('8-9PM', '8:00 PM - 9:00 PM')], default='0', max_length=100),
        ),
    ]
